name: Build image and push to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Node app
        run: |
          cd $GITHUB_WORKSPACE/web
          npm install
          npm run build

      - name: Build and push Docker Nginx image
        run: |
          docker buildx create --use
          docker buildx build \
            --cache-from ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-nginx:latest \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-nginx:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            --file Dockerfile.nginx .